name: CI

on:
  pull_request:
  push:
    branches:
      - "main"

permissions:
  contents: read

jobs:
  format_and_lint:
    name: Check Format and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20.11.x
          cache: npm

      - name: Install
        run: npm install

      - name: Prettier
        run: npm run format:check

      - name: Lint
        run: SKIP_ENV_VALIDATION=true npm run lint

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20.11.x
          cache: npm

      - name: Install
        run: npm install

      - name: Build Nextjs App
        run: SKIP_ENV_VALIDATION=true npm run build
